---
language: go

go:
  - 1.5.2

install:
    - go get -v github.com/spf13/hugo
    - openssl aes-256-cbc -K $encrypted_88b8e944af1a_key -iv $encrypted_88b8e944af1a_iv -in key.pem.enc -out key.pem -d

script: ./deploy.sh

branches:
  only:
  - master

git:
  depth: 3

