---
language: go

go:
  - 1.5.2

before_install:
    - |
      openssl aes-256-cbc -K $encrypted_88b8e944af1a_key -iv $encrypted_88b8e944af1a_iv -in key.pem.enc -out key.pem -d
      eval "$(ssh-agent -s)" #start the ssh agent
      chmod 600 key.pem # this key should have push access
      ssh-add key.pem

install:
    - go get -v github.com/spf13/hugo
    - pip install virtualenv

script:
    - |
        virtualenv -p /usr/bin/python2.7 --system-site-packages env
        source env/bin/activate
        pip install -r requirements.txt
        git clone git@github.com:ewok/ewok.github.io.git public
        hugo
        cd public
        git config --global user.email "ewok@ewok.ru"
        git config --global user.name "Artur"
        git add --all :/
        msg="rebuilding site `date`"
        git commit -m "$msg"
        cd ../docs
        mkdocs build --clean
        cd ..
        rm -rf public/docs
        mv docs/site public/docs
        cd public
        git add --all :/
        msg="rebuilding docs `date`"
        git commit -m "$msg"
        git push origin master
        cd ..

branches:
  only:
  - master

git:
  depth: 3

cache:
  directories:
  - $HOME/gopath

before_cache:
    - cd $HOME
    - rm -rf $HOME/gopath/src/github.com/ewok
