baseurl: "https://ewok.github.io/"
languagecode: "ru_RU"
title: "Записки Турыча"
theme: beg

disqusshortname: "ewokru"

Params:
  author: "Artur Taranchiev"
  dateform: "Mon, Jan 2, 2006"
  # GoogleAnalyticsUserID: "Your ID."
  # Facebook: "Your ID."
  twitter: "ewokru"
  github: "ewok"
  showRelatedpost: True
  syntaxhighlighttheme: "solarized_dark.min.css"
  googlecs: "018232319146837403043:ugnaw2yq0s8"
  yandexmetrika: "22971493"

Indexes:
  tag: "tags"

permalinks:
    post: /:slug

MetadataFormat: "yaml"

menu:
    main:
      - Name: "Docs"
        Weight: -120
        Identifier: "docs"
        Url: "/docs"
      - Name: "GitHub"
        Pre: "<i class='fa fa-heart'></i>"
        Weight: -110
        Identifier: "github"
        Url: "https://github.com/ewok"
      - Name: "Twitter"
        Pre: "<i class='fa fa-road'></i>"
        Weight: -100
        Url: "https://twitter.com/ewokru"

