BaseUrl: "https://ewok.github.io/"
LanguageCode: "ru_RU"
Title: "Записки Турыча"
Theme: beg

Params:
  Author: "Artur Taranchiev"
  DateForm: "Mon, Jan 2, 2006"
  # GoogleAnalyticsUserID: "Your ID."
  # Facebook: "Your ID."
  Twitter: "ewokru"
  Github: "ewok"
  ShowRelatedPost: True
  disqusShortname: "ewokru"
  SyntaxHighlightTheme: "solarized_dark.min.css"
  GoogleCS: 018232319146837403043:ugnaw2yq0s8
  YandexMetrika: "22971493"

Indexes:
  tag: "tags"

permalinks:
    post: /:slug

MetadataFormat: "yaml"

menu:
    main:
      - Name: "Docs"
        Weight: -120
        Identifier: "docs"
        Url: "/docs"
      - Name: "GitHub"
        Pre: "<i class='fa fa-heart'></i>"
        Weight: -110
        Identifier: "github"
        Url: "https://github.com/ewok"
      - Name: "Twitter"
        Pre: "<i class='fa fa-road'></i>"
        Weight: -100
        Url: "https://twitter.com/ewokru"

